@baseurl = http://127.0.0.1:8000/api/v1
@token =  2|valmhpMRKSzLr7i3Tt5fRgfziUXxE5SsQhGKJZA56b8c6431

### UPDATE ONE ANNOUNCEMENT WITH VALID DATES
PUT {{baseurl}}/announcements/dates/48 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{token}}
Accept: application/json

&start_date=2024-01-20
&end_date=2024-01-24


### UPDATE ONE ANNOUNCEMENT WITH EMPTY DATES
PUT {{baseurl}}/announcements/dates/48 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{token}}
Accept: application/json


### UPDATE ONE ANNOUNCEMENT WITH INVALID DATES
PUT {{baseurl}}/announcements/dates/2 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{token}}
Accept: application/json

&start_date=324324
&end_date=@$%@%@


### UPDATE ONE ANNOUNCEMENT WITH INVALID SCHEDULE
PUT {{baseurl}}/announcements/dates/2 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{token}}
Accept: application/json

&start_date=2024-01-20
&end_date=2024-01-16